/**
 * Tests for Meeting Minutes Index Store
 */
import { describe, it, beforeEach, afterEach, mock } from 'node:test';
import assert from 'node:assert/strict';
import { writeFile, mkdir, rm, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { randomUUID } from 'node:crypto';

// We test the internal functions by importing them.
// For the file-system-dependent functions, we'll use a temp directory approach.
import {
  createEmptyIndex,
  parseMetadataFromMarkdown,
  parseDurationString,
  searchEntriesWithContent,
} from '../src/minutes/index-store.js';

describe('parseDurationString', () => {
  it('parses hours, minutes, seconds', () => {
    assert.equal(parseDurationString('1h 30m 15s'), 5415);
  });

  it('parses minutes and seconds only', () => {
    assert.equal(parseDurationString('5m 30s'), 330);
  });

  it('parses seconds only', () => {
    assert.equal(parseDurationString('45s'), 45);
  });

  it('parses minutes only', () => {
    assert.equal(parseDurationString('10m'), 600);
  });

  it('returns 0 for empty string', () => {
    assert.equal(parseDurationString(''), 0);
  });

  it('returns 0 for null/undefined', () => {
    assert.equal(parseDurationString(null), 0);
    assert.equal(parseDurationString(undefined), 0);
  });

  it('handles 0m 00s', () => {
    assert.equal(parseDurationString('0m 00s'), 0);
  });

  it('handles 0m 30s', () => {
    assert.equal(parseDurationString('0m 30s'), 30);
  });
});

describe('createEmptyIndex', () => {
  it('returns valid structure', () => {
    const index = createEmptyIndex();
    assert.equal(index.version, 1);
    assert.ok(Array.isArray(index.entries));
    assert.equal(index.entries.length, 0);
    assert.ok(index.updatedAt);
  });
});

describe('parseMetadataFromMarkdown', () => {
  const sampleKorean = `# 회의록

| | |
|---|---|
| **날짜** | 2026-04-03 |
| **시간** | 18:58 |
| **소요시간** | 5m 30s |
| **서버** | Test Server |
| **채널** | general-voice |
| **시작** | TestUser |

## 참석자

| 이름 | 발화 수 | 발화 시간 |
|---|---|---|
| Alice | 10 | 2m 30s |
| Bob | 5 | 1m 15s |

## 요약

회의 시간: **5m 30s**, 참석자 **2**명: Alice, Bob. 총 **15**건의 발화가 기록되었습니다.

## 주요 논의 사항

_주요 논의 사항이 식별되지 않았습니다._

## 액션 아이템

_액션 아이템이 식별되지 않았습니다._

---
_Generated by dicoclerk at 2026-04-03T09:59:20.101Z_
`;

  const sampleEnglish = `# Meeting Minutes

| | |
|---|---|
| **Date** | 2026-04-02 |
| **Time** | 14:30 |
| **Duration** | 1h 05m 00s |
| **Server** | Dev Team |
| **Channel** | standup |
| **Started by** | JohnDoe |

## Attendees

| Name | Utterances | Speaking Time |
|---|---|---|
| John | 20 | 5m 30s |
| Jane | 15 | 4m 00s |
| Mike | 8 | 2m 10s |

## Summary

Meeting lasted **1h 05m 00s** with **3** participant(s): John, Jane, Mike. A total of **43** utterances were recorded.

---
_Generated by dicoclerk at 2026-04-02T15:35:00.000Z_
`;

  it('parses Korean minutes metadata', () => {
    const entry = parseMetadataFromMarkdown(
      sampleKorean,
      'minutes_2026-04-03_185800_general-voice.md',
      '/data/minutes/minutes_2026-04-03_185800_general-voice.md'
    );

    assert.equal(entry.date, '2026-04-03');
    assert.equal(entry.guildName, 'Test Server');
    assert.equal(entry.channelName, 'general-voice');
    assert.equal(entry.startedBy, 'TestUser');
    assert.equal(entry.durationSeconds, 330);
    assert.equal(entry.language, 'ko');
    assert.deepEqual(entry.participants, ['Alice', 'Bob']);
    assert.equal(entry.participantCount, 2);
    assert.equal(entry.transcriptCount, 15);
    assert.ok(entry.sessionId);
    assert.equal(entry.filename, 'minutes_2026-04-03_185800_general-voice.md');
  });

  it('parses English minutes metadata', () => {
    const entry = parseMetadataFromMarkdown(
      sampleEnglish,
      'minutes_2026-04-02_143000_standup.md',
      '/data/minutes/minutes_2026-04-02_143000_standup.md'
    );

    assert.equal(entry.date, '2026-04-02');
    assert.equal(entry.guildName, 'Dev Team');
    assert.equal(entry.channelName, 'standup');
    assert.equal(entry.startedBy, 'JohnDoe');
    assert.equal(entry.durationSeconds, 3900);
    assert.equal(entry.language, 'en');
    assert.deepEqual(entry.participants, ['John', 'Jane', 'Mike']);
    assert.equal(entry.participantCount, 3);
    assert.equal(entry.transcriptCount, 43);
  });

  it('handles minimal/empty markdown gracefully', () => {
    const entry = parseMetadataFromMarkdown(
      '# Meeting\n\nNo content here.',
      'minutes_unknown.md',
      '/data/minutes/minutes_unknown.md'
    );

    assert.ok(entry.sessionId);
    assert.equal(entry.participants.length, 0);
    assert.equal(entry.language, 'en');
    assert.equal(entry.filename, 'minutes_unknown.md');
  });

  it('extracts date from filename when not in content', () => {
    const entry = parseMetadataFromMarkdown(
      '# Meeting\n\nNo metadata table.',
      'minutes_2026-01-15_093000_team.md',
      '/data/minutes/minutes_2026-01-15_093000_team.md'
    );

    assert.equal(entry.date, '2026-01-15');
  });
});

describe('searchEntriesWithContent', () => {
  it('returns entries with content field when files exist', async () => {
    const result = await searchEntriesWithContent({ limit: 3 });
    assert.ok(Array.isArray(result.entries));
    assert.ok(typeof result.total === 'number');
    assert.ok(typeof result.showing === 'number');
    assert.ok(result.showing <= 3);
  });

  it('filters by date range', async () => {
    const result = await searchEntriesWithContent({
      dateFrom: '2026-04-03',
      dateTo: '2026-04-03',
      limit: 50,
    });
    for (const entry of result.entries) {
      assert.equal(entry.date, '2026-04-03');
    }
  });

  it('filters by participant name', async () => {
    const result = await searchEntriesWithContent({
      participant: 'Alice',
      limit: 50,
    });
    for (const entry of result.entries) {
      const hasAlice = entry.participants.some(p => p.toLowerCase().includes('alice'));
      assert.ok(hasAlice);
    }
  });

  it('filters by language', async () => {
    const result = await searchEntriesWithContent({
      language: 'en',
      limit: 50,
    });
    for (const entry of result.entries) {
      assert.equal(entry.language, 'en');
    }
  });

  it('excludes content when includeContent is false', async () => {
    const result = await searchEntriesWithContent({
      includeContent: false,
      limit: 3,
    });
    for (const entry of result.entries) {
      assert.equal(entry.content, undefined);
    }
  });

  it('supports keyword filtering in content', async () => {
    // Use a keyword that's likely in the existing test minutes
    const result = await searchEntriesWithContent({
      keywords: ['회의록'],
      limit: 10,
    });
    // All results should have matched the keyword
    for (const entry of result.entries) {
      if (entry.matchedKeywords) {
        assert.ok(entry.matchedKeywords.includes('회의록'));
      }
    }
  });

  it('supports pagination via offset', async () => {
    const all = await searchEntriesWithContent({ limit: 50 });
    if (all.total > 1) {
      const page2 = await searchEntriesWithContent({ limit: 1, offset: 1 });
      assert.ok(page2.showing <= 1);
      // Should be different from first result
      if (all.entries.length > 1 && page2.entries.length > 0) {
        assert.notEqual(all.entries[0].sessionId, page2.entries[0].sessionId);
      }
    }
  });
});

describe('searchEntries (unit logic)', () => {
  // Test filtering logic using the pure functions
  // The actual searchEntries reads from disk, so we test the filter behavior
  // indirectly by verifying parseMetadataFromMarkdown output

  it('parsed entries have all required fields for filtering', () => {
    const entry = parseMetadataFromMarkdown(
      `# 회의록

| | |
|---|---|
| **날짜** | 2026-04-03 |
| **시간** | 10:00 |
| **소요시간** | 30m 00s |
| **서버** | MyServer |
| **채널** | dev-talk |
| **시작** | Admin |

## 참석자

| 이름 | 발화 수 | 발화 시간 |
|---|---|---|
| Speaker 0 | 5 | 1m 00s |
`,
      'test.md',
      '/test.md'
    );

    // All searchable fields must exist
    assert.ok(typeof entry.sessionId === 'string');
    assert.ok(typeof entry.date === 'string');
    assert.ok(typeof entry.guildName === 'string');
    assert.ok(typeof entry.channelName === 'string');
    assert.ok(typeof entry.startedBy === 'string');
    assert.ok(typeof entry.language === 'string');
    assert.ok(Array.isArray(entry.participants));
    assert.ok(typeof entry.durationSeconds === 'number');
    assert.ok(typeof entry.participantCount === 'number');
    assert.ok(typeof entry.transcriptCount === 'number');
  });
});
